//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HertZ_ExcelAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HertZ_ExcelAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] _2019国企财务报表附注 {
            get {
                object obj = ResourceManager.GetObject("2019国企财务报表附注", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap DivisionSign {
            get {
                object obj = ResourceManager.GetObject("DivisionSign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap HertZ_Logo {
            get {
                object obj = ResourceManager.GetObject("HertZ_Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon HZlogo32 {
            get {
                object obj = ResourceManager.GetObject("HZlogo32", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 工作表名称,一级标题,二级标题,表格类型,表格顺序,备注
        ///Z20 成本费用情况表(企财20表),八、财务报表主要项目注释,54、销售费用,2,0,
        ///Z20 成本费用情况表(企财20表)1,八、财务报表主要项目注释,54、销售费用,0,1,
        ///Z20 成本费用情况表(企财20表)2,八、财务报表主要项目注释,55、管理费用,0,1,
        ///QCF09 货币资金(附注09表),八、财务报表主要项目注释,1、货币资金,1,1,
        ///QCF10 受限制的货币资金明细(附注10表),八、财务报表主要项目注释,1、货币资金,5,2,
        ///QCF12 以公允价值计量且其变动计入当期损益的金融资产(附注,八、财务报表主要项目注释,2、以公允价值计量且其变动计入当期损益的金融资产,1,1,
        ///QCF13 衍生金融资产(附注13表),八、财务报表主要项目注释,3、衍生金融资产,5,1,
        ///QCF14 应收票据(附注14表),八、财务报表主要项目注释,4、应收票据,1,1,
        ///QCF15 已质押的应收票据(附注15表),八、财务报表主要项目注释,4、应收票据,1,2,
        ///QCF16 已背书或贴现且资产负债表日尚未到期的应收票据(附注, [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string JiuQiDB {
            get {
                return ResourceManager.GetString("JiuQiDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MinusSign {
            get {
                object obj = ResourceManager.GetObject("MinusSign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap MultiplicationSign {
            get {
                object obj = ResourceManager.GetObject("MultiplicationSign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap PlusSign {
            get {
                object obj = ResourceManager.GetObject("PlusSign", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Byte[] 类型的本地化资源。
        /// </summary>
        internal static byte[] 往来询证函模板 {
            get {
                object obj = ResourceManager.GetObject("往来询证函模板", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
